# Generated by Django 4.2.4 on 2023-09-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wishes", "0002_wishesinformation_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WishModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="wishesinformation",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="wishesinformation",
            name="updated_at",
        ),
    ]
