# Generated by Django 4.2.4 on 2023-09-07 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wishes", "0006_wishtext"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedWish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name="WishesInformation",
            new_name="WishInformation",
        ),
        migrations.DeleteModel(
            name="WishText",
        ),
        migrations.AddField(
            model_name="generatedwish",
            name="wish_information",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="wishes.wishinformation"
            ),
        ),
    ]
